name: ecommerce
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.13.1 <3.0.0' #">=2.14.0-136.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #FOR DYNAMIC UI
  flutter_screenutil:

  #FOR STATE MANAGEMENT AND SESSION MANAGE
  get:
  get_storage:

  image_picker:
  image_cropper:

  #FOR DATE FORMATTING
  intl:

  #FOR API CALLING
  dio:

  #FOR FIREBASE
  firebase_core: 1.2.0
  firebase_auth: 1.2.0
  cloud_firestore: 2.2.0

  # onesignal_flutter:

  # value equality
  equatable:

  # AUTHENTICATION
  flutter_facebook_auth:
  google_sign_in: ^5.0.4

  # FOR FONT
  google_fonts:

  configurable_expansion_tile:

  # FOR EVENT HANDLE
  event_bus:

  crypto:

  # ICON
  line_icons:

  # IMAGE
  cached_network_image:

  # FOR KEYSTORE GENERATE ANDROID (GET SH1)
  flutter_automation:

  # FOR WEB URL OPEN
  webview_flutter:

  # FOR DEVICE INFORMATION
  device_info:

  # FOR INTERNET CHECK
  connectivity:

  # FOR UNIQUE ID
  uuid:

  flutter_config:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # FOR IMAGE

  # FOR FONT

