name: ecommerce
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #FOR DYNAMIC UI
  flutter_screenutil:

  #FOR STATE MANAGEMENT AND SESSION MANAGE
  get:
  get_storage:

  image_picker:
  image_cropper:

  #FOR DATE FORMATTING
  intl:

  #FOR API CALLING
  dio:

  #FOR FIREBASE
  firebase_core:
  firebase_auth:
  cloud_firestore:

  # AUTHENTICATION
  flutter_facebook_auth:
  google_sign_in:

  # FOR FONT
  google_fonts:

  # FOR EVENT HANDLE
  event_bus:

  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #FOR IMAGE

  #FOR FONT

